### ISSUE TITLE
bitmask-overlay

### ISSUE THREAD

**Issue by MeisterP** [hnaparst/overlay#1]
I've moved your bitmask related ebuilds into a dedicated overlay and added the necessary dependencies.

I've started working on bitmask/leapcode related ebuilds some time ago and did not yet merge all my changes. It's still work in progress.

https://github.com/MeisterP/bitmask-overlay

Are you interested in contributing? We could work with either pull requests or I could add you to the contributors.

**Comment by Harold-Anderson** [comment]
I have submitted all my ebuilds to bugs.gentoo.org today.

https://bugs.gentoo.org/show_bug.cgi?id=531554
https://bugs.gentoo.org/show_bug.cgi?id=531556
https://bugs.gentoo.org/show_bug.cgi?id=531558[1]
https://bugs.gentoo.org/show_bug.cgi?id=531560[2]
https://bugs.gentoo.org/show_bug.cgi?id=531562[3]
https://bugs.gentoo.org/show_bug.cgi?id=531564
https://bugs.gentoo.org/show_bug.cgi?id=531566
https://bugs.gentoo.org/show_bug.cgi?id=531568
https://bugs.gentoo.org/show_bug.cgi?id=531570
https://bugs.gentoo.org/show_bug.cgi?id=531572
https://bugs.gentoo.org/show_bug.cgi?id=531574
https://bugs.gentoo.org/show_bug.cgi?id=531576

Actually, the suite of ebuilds in my overlay works well. It produces the
working 0.6.0 client. How much have you accomplished? Do you have more
than that?

Kind Regards.

On Thu, Dec 4, 2014, at 06:33 PM, Poncho wrote:

> I've moved your bitmask related ebuilds into a dedicated overlay and
> added the necessary dependencies.
> 
> I've started working on bitmask/leapcode related ebuilds some time ago
> and did not yet merge all my changes. It's still work in progress.
> 
> https://github.com/MeisterP/bitmask-overlay
> 
> Are you interested in contributing? We could work with either pull
> requests or I could add you to the contributors.
> 
> — Reply to this email directly or view it on GitHub[4].

Links:
1. https://bugs.gentoo.org/show_bug.cgi?id=531568
2. https://bugs.gentoo.org/show_bug.cgi?id=531568
3. https://bugs.gentoo.org/show_bug.cgi?id=531568
4. https://github.com/hnaparst/overlay/issues/1

**Comment by Harold-Anderson** [comment]
Actually, thinking about it, I think it is best to just leave the code
in my overlay because:
1. The LEAP project already has been notified about my working client,
   and they are discussing the best way to document it.
2. I have already submitted the location of my ebuilds to Gentoo.
3. I doesn't appear that your overlay has anything over and above mine.
4. My overlay is already part of layman.

So all in all, it would just create confusion and not add anything to
the process to change the location. If you have code contributions,
please submit a pull request to me.

Kind Regards,

Harold

**Comment by MeisterP** [comment]
Well, the improvements so far are:
- a clean repoman full output
- not depending an various other overlays (virtual/python-argparse, dev-python/scrypt, dev-db/sqlcipher)

There are other issues. Like wrong LICENSE variables, missing ${PYTHON_USEDEP}, wrong PYTHON_COMPAT variables, unnecessary eclasses in inherit and missing dependencies.
