### ISSUE TITLE
re: 367.35 driver and 4.7.4-ck

### ISSUE THREAD

**Issue by thunderrd** [hnaparst/overlay#10]
Hi again, I've replaced my legacy GPU with a Fermi card [GTX 480] and would like to use your 367.35 nvidia-drivers [because I know you have the right patches for the ck-sources].

I've built the module successfully against the 4.7.4-ck kernel, but it seems to have this [rather old] bug: 
https://bugs.gentoo.org/show_bug.cgi?id=564096

It also seems not to allow me to set the fan speed using the following in .xinitrc:

[this sets nvidia thermal applet to 'on', and fan control to 'x'%]
nvidia-settings -a [gpu:0]/GPUFanControlState=1
nvidia-settings -a [fan:0]/GPUCurrentFanSpeed=75

The first line is allowed, but the second one complains about some read-only permissions:

ERROR: The attribute 'GPUCurrentFanSpeed' specified in assignment '[fan:0]/GPUCurrentFanSpeed=90' cannot be assigned (it is a read-only attribute)

I know this isn't a support channel, but could you advise me whether I'm dealing with a kernel or a driver problem?  Both of the above are deal-breakers for me, so if I can't solve them I'm stuck on the legacy driver, even though I don't have legacy hardware anymore.

Thanks for any advice you might have.

**Comment by thunderrd** [comment]
Interestingly enough, I read the bug a bit more deeply and found that downgrading to nvidia-drivers-355.11-r2 should solve the tty switching problem, and that is the major issue for me.

However, I can't seem to build that version with any of my installed kernels [4.6.5, 4.7.3, 4.7.4].  Can you point me to the right patches to build that nvidia version?

**Comment by Harold-Anderson** [comment]
I will look into it.  In the meantime, please stick with 4.7.4.  There have been major revisions to the kernel, and Con Kolivas has also done a huge amount of work on his patchset in the past couple of weeks.  I have the correct patches for 4.7.4, but I did not bother putting the new patches into the older versions of 4.7.x

**Comment by Harold-Anderson** [comment]
First, you cannot use the 4.7.x kernel series with older versions of the nvidia driver than 367.35-r2.  And in fact, you should at this point be using Gentoo's nvidia-drivers.  The version I have in my repo was a one-off to work with 4.7.x before an official nvidia driver was produced to work with kernel 4.7.

The nvidia-driver I have in my repo has nothing to do with Con Kolivas' patchset.

To answer your question, the issue you are reporting is absolutely a shortcoming of the nvidia driver, and Nvidia has themselves opened a bug on it.  In the meantime, it seems that you can avoid the problem by compiling your kernel with these options

```
# CONFIG_FB_BOOT_VESA_SUPPORT is not set
# CONFIG_FB_UVESA is not set
# CONFIG_FB_VESA is not set
```

Wtith those options, I am able to do VT switching with no problem with the nvidia-drivers-370.28 and ck-sources-4.7.4

**Comment by thunderrd** [comment]
Thanks Harold for looking into it.

Actually, the legacy 340.96 works fine with 4.7.4.  That's what I have running now.  I tried the 370 in portage first, and then tried your one-off as a test.  Unless there is something I'm missing, 340.96 can be used as a fallback [at least on my box].

I tried both the 370 in portage, and your 367, but they both exhibit the same tty behavior, for which you may have just given me the solution.  I do have CONFIG_FB_UVESA=y, so I'll try changing that now.

Oh, and I've just seen something regarding my fan speed problem.  It _might_ be a syntax change in later nvidia-driver versions:

nvidia-settings -a [fan:0]/GPUCurrentFanSpeed=75
_might_ now be:
nvidia-settings -a [fan:0]/GPUTargetFanSpeed=75

I'll check this out as well, and let you know.

Thanks again

**Comment by thunderrd** [comment]
OK, yes, both of my issues are solved.  Unsetting FB_UVESA fixes the tty problem [although I had it set to enable the FB and give me good-looking tty fonts, which are now gone].  That's a minor problem, though, and will probably be fixed in the driver, given time.

The nvidia-settings issue is likewise solved by changing that line I mentioned above.  Apparently it was changed in the code sometime after 340.x, and so anyone coming up from the legacy driver to the current versions will encounter it if setting the fanspeed when starting X.

Can you link me to the nvidia bug you referred to above?  I may not be using the right search terms, but I can't locate it.

Regards and thanks!

**Comment by Harold-Anderson** [comment]
https://devtalk.nvidia.com/default/topic/912455

**Comment by thunderrd** [comment]
Hey, FWIW, I've tested and found out that I can use CONFIG_FB_VESA=y, and it works fine with 370/4.7.4 on my machine.  So my better-looking console resolution is back.  Seems that UVESA was the buggy option, at least for me.

**Comment by Harold-Anderson** [comment]
I actually knew that, but I was too lazy to be clear originally.  Actually the problem is v86d, a daemon that uvesafb uses.  Sorry for being imprecise.
