### ISSUE TITLE
The 'secretstorage' distribution was not found and is required by keyring

### ISSUE THREAD

**Issue by Nowa-Ammerlaan** [hnaparst/overlay#11]
I'm not sure if this is something I did or not, but I tried starting bitmask today (haven't used it in about a month or two) and it failed, error output below:
`andrew@Andrew-Gentoo ~ $ bitmask --verbose
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/bitmask", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2900, in <module>
    @_call_aside
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2886, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 942, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'secretstorage' distribution was not found and is required by keyring`

A quick google search later, I tried to install the secretstorage python module using pip (since I can't find it in portage). However this module wants to be installed using pip as root, which apparently isn't a good idea according to the gentoo wik. Anyway, it seems bitmask (0.9.1) is missing a dependency. I also tried version 0.9.1-r1 which gave the same error.

**Comment by Harold-Anderson** [comment]
The latest version I have in my overlay is 0.9.2.  However, I do not guarantee that it will work either.   I have never seen a reference to secretstorage before.  Give 0.9.2 from my overlay a try and let me know what happens.  If you need secretstorage, I will add that to my overlay.

**Comment by Nowa-Ammerlaan** [comment]
I didn't test that version because I have a dependency conflict, bitmask_client-0.9.2 requires <gnupg-1.4 but gnome-keyring requires >=gnupg-2.0.28. And thunderbird/gnupg, requires pinentry which requires libsecret which also requires gnome-keyring. So long story short I can't install both thunderbird and bitmask_client-0.9.2. I believe I tried to force the install some months before, but if I recall correctly there was some other problem.

**Comment by Harold-Anderson** [comment]
I hate to say it, but bitmask is not in a runnable state right now.  The best advice is to wait until they release a new version.  I tried to emerge 0.9.2, and it fails because pysqlcipher is completely unmergable.   This is another leap.se special item that they seem to be actively changing.

**Comment by Nowa-Ammerlaan** [comment]
I have pysqlcipher-2.6.24 installed on my system, however when I try to rebuild it it also fails on my system. Anyway I'll just wait for the next version. Also, when I import keyring in python it does not give any error, so it's not a keyring problem. I have been unable to narrow the problem down further, but I'll report it on the LEAP issue tracker.

**Comment by Nowa-Ammerlaan** [comment]
I'm closing this since we now have `net-vpn/riseup-vpn` in `::gentoo`.
