### ISSUE TITLE
sys-kernel/ck-sources should advertise upstream compatibility

### ISSUE THREAD

**Issue by flberger** [hnaparst/overlay#12]
Kolivas announced on 16th Jan 2017:

>  I've fallen back to only syncing up with major releases. I'm still on 4.9.0-ck1 myself.

Source: [ck-hack.blogspot.de](https://ck-hack.blogspot.de/2016/12/linux-49-ck1-muqss-version-0150.html?showComment=1484540302548#c9158703213417372307)

As the overlay at the time of writing provides ck-sources-4.9.1, 4.9.2, 4.9.3 and 4.9.4, these ebuilds should probably display a post-install message that minor releases are currently not supported by upstream.

**Comment by Harold-Anderson** [comment]
Hmm.   This does not seem to me to be a change in Con Kolivas' policy.  He has always published patch sets without tying them to specific minor versions, and does not offer upstream support except when he feels like it.  Unless I am mistaken...

It seems reasonable to add post-install text if we are aware that users have had bad experiences, of course.

**Comment by Harold-Anderson** [comment]
Removed everything after 4.9.0, since they are unsupported by upstream.  Thanks!
