### ISSUE TITLE
linux-4.10-ck1 + MuQSS v0.152  is out

### ISSUE THREAD

**Issue by flberger** [hnaparst/overlay#13]
See https://ck-hack.blogspot.de/2017/02/linux-410-ck1-muqss-version-0152-for.html .

A gentle reminder for a ck-sources ebuild update. :-)

**Comment by Harold-Anderson** [comment]
Do you think this is necessary now that it appears someone is publishing an e-build in the main gentoo repository?

**Comment by flberger** [comment]
We have yet to see whether this ebuild will be actually maintained. I have filed a version bump request at https://bugs.gentoo.org/show_bug.cgi?id=610406

I personally wouldn't mind if your overlay followed -ck releases for a little longer. :-)

**Comment by Harold-Anderson** [comment]
I am not sure what this would add to the process, unless you think there is some shortcoming with the Gentoo ebuild.  I would also mention that Con Kolivas does not support or recommend using his patchset for minor versions of the kernel other than the one that he released the patchset for.  For the 4.9.x series, this means that only 4.9.0-ck was supported.  The only thing I could conceivable do is release a version 4.10.0-ck, unless Con produces another patchset later in the 4.10.x series.

**Comment by flberger** [comment]
Gentoo ebuild looks maintained and has been updated quickly. Closing.
