### ISSUE TITLE
Can't use brackets because of this strange menu bar bug #13738

### ISSUE THREAD

**Issue by Harold-Anderson** [hnaparst/overlay#14]
https://github.com/adobe/brackets/issues/13738

**Comment by linxon** [comment]
what you think about this? 

https://github.com/adobe/brackets/issues/13731

**Comment by Harold-Anderson** [comment]
https://github.com/adobe/brackets/issues/13731#issuecomment-332564712



On Wed, Sep 27, 2017, at 08:27 AM, Yury Martynov wrote:
> what you can say about this?


> adobe/brackets#13731[1]


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/adobe/brackets/issues/13731
  2. https://github.com/hnaparst/overlay/issues/14#issuecomment-332559488
