### ISSUE TITLE
Slotting Kernels (ck-sources ebuilds)

### ISSUE THREAD

**Issue by jorgicio** [hnaparst/overlay#2]
Hi!

As a suggestion, a kernel-related ebuild must be slotted. So please, add this:

SLOT="${PV}"

in the ck-sources ebuilds. Right between the line of the IUSE, and the homepage.

Thanks.

**Comment by Harold-Anderson** [comment]
My guess is that this is done by the kernel-2 eclass, since the ebuilds in portage do not contain this tag.
For instance, 
http://data.gpo.zugaina.org/gentoo/sys-kernel/gentoo-sources/gentoo-sources-3.18.1.ebuild

**Comment by jorgicio** [comment]
Thanks, so eix is showing me things wrong.

hackenherr ~ # eix ck-sources                                                                                                                                                          [9:45:17]
[U?] sys-kernel/ck-sources
     Available versions:  
     (3.4.104) (~)3.4.104^bs
     (0)    (~)3.4.104[1](~)3.10.60[1](~)3.10.61[1](~)3.10.62[1](~)3.10.63[1](~)3.12.32[1](~)3.12.34[1](~)3.14.24[1](~)3.14.26[1](~)3.14.27[1](~)3.17.3[1](~)3.17.4[1](~)3.17.6[1](~)3.17.7[1](~)3.18.0[1](~)3.18.1[1](3.10.62) (~)3.10.62^bs
     (3.12.34) (~)3.12.34^bs
     (3.14.26) (~)3.14.26^bs
     (3.17.6) (~)3.17.6^bs
     (3.18.0) (~)3.18.0^bs
       {bfsonly build deblob experimental symlink urwlocks}
     Installed versions:  3.18.1(3.18.1)^bs[1](02:38:18 20/12/14)(bfsonly symlink -build -deblob)
     Homepage:            http://dev.gentoo.org/~mpagano/genpatches/ http://users.on.net/~ckolivas/kernel/
     Description:         Full Linux . kernel sources with Con Kolivas' high performance patchset and Gentoo's genpatches

[1] "hnaparst" /var/lib/layman/hnaparst
