### ISSUE TITLE
Wrong Genpatches in ck-sources-3.18.4

### ISSUE THREAD

**Issue by jorgicio** [hnaparst/overlay#4]
Hi! Thanks for the New version of the kernel. However, you put the wrong genpatches on that version. In the ebuild, the line says:

K_GENPATCHES_VER="5"

But it must be:

K_GENPATCHES_VER="6"

Please, fix that.

Thanks.

**Comment by Harold-Anderson** [comment]
Sorry, I forgot to stage my changes before committing them. Now it
should be correct.

Kind Regards

On Thu, Jan 29, 2015, at 10:57 PM, Jorge Pizarro Callejas wrote:

> Hi! Thanks for the New version of the kernel. However, you put the
> wrong genpatches on that version. In the ebuild, the line says:
> 
> K_GENPATCHES_VER="5"
> 
> But it must be:
> 
> K_GENPATCHES_VER="6"
> 
> Please, fix that.
> 
> Thanks.
> 
> — Reply to this email directly or view it on GitHub[1].

Links:
1. https://github.com/hnaparst/overlay/issues/4
