### ISSUE TITLE
New kernel version: 3.19.1

### ISSUE THREAD

**Issue by jorgicio** [hnaparst/overlay#5]
Please, if you can, upgrade, because I tried locally, and I got some problems at patching.

Thanks :D 

http://pastebin.com/VfpETBWc

**Comment by Harold-Anderson** [comment]
It might take me several days before I look at it.  I had a very long and difficult week.

**Comment by Harold-Anderson** [comment]
Give it a try.  I removed the experimental patches, which weren't being used by gentoo-sources anyway.

**Comment by jorgicio** [comment]
Oh, I see...
And so is what it wasn't compile. Now it works. Thanks!
