### ISSUE TITLE
dev-python/pysqlite-2.6.3::hnaparst failed (install phase)

### ISSUE THREAD

**Issue by Nowa-Ammerlaan** [hnaparst/overlay#6]
I'm getting an error when trying to install pysqlite:
python_execute_function() is invalid for python-r1 suite, please take a look @ https://wiki.gentoo.org/wiki/Project:Python/Python.eclass_conversion#python_execute_function
- 
- Call stack:
-     ebuild.sh, line  133:  Called src_install
-   environment, line 3612:  Called python_execute_function '-q' 'delete_tests'
-   environment, line 2800:  Called die
- The specific snippet of code:
-       die "${FUNCNAME}() is invalid for python-r1 suite, please take a look @ https://wiki.gentoo.org/wiki/Project:Python/Python.eclass_conversion#python_execute_function"
- 
- If you need support, post the output of `emerge --info '=dev-python/pysqlite-2.6.3::hnaparst'`,
- the complete build log and the output of `emerge -pqv '=dev-python/pysqlite-2.6.3::hnaparst'`.
- The complete build log is located at '/var/tmp/portage/dev-python/pysqlite-2.6.3/temp/build.log'.
- The ebuild environment file is located at '/var/tmp/portage/dev-python/pysqlite-2.6.3/temp/environment'.
- Working directory: '/var/tmp/portage/dev-python/pysqlite-2.6.3/work/pysqlite-2.6.3'
- S: '/var/tmp/portage/dev-python/pysqlite-2.6.3/work/pysqlite-2.6.3'

> > > Failed to emerge dev-python/pysqlite-2.6.3, Log file:
> > >  '/var/tmp/portage/dev-python/pysqlite-2.6.3/temp/build.log'

Andrew-Gentoo andrew # emerge --info =dev-python/pysqlite-2.6.3::hnaparst | wgetpaste
Your paste can be seen here: https://bpaste.net/show/197cbd16b6e6
Andrew-Gentoo andrew # emerge -pqv =dev-python/pysqlite-2.6.3::hnaparst | wgetpaste
Your paste can be seen here: https://bpaste.net/show/7d7864507b87
Andrew-Gentoo andrew # cat /var/tmp/portage/dev-python/pysqlite-2.6.3/temp/build.log | wgetpaste
Your paste can be seen here: https://bpaste.net/show/76ce595baf3d
Andrew-Gentoo andrew # cat /var/tmp/portage/dev-python/pysqlite-2.6.3/temp/environment | wgetpaste
Your paste can be seen here: https://bpaste.net/show/74c2bb8a8405
Andrew-Gentoo andrew #

**Comment by Harold-Anderson** [comment]
OK, it should work now.  Thanks for pointing it out.
