### ISSUE TITLE
Missing use flag: bundled dependency when emerging bitmask_client

### ISSUE THREAD

**Issue by Nowa-Ammerlaan** [hnaparst/overlay#7]
When trying to emerge bitmask_client, emerge complains about missing use flag bundled in dev-python/pyzmq . This use flag is indeed missing in the pyzmq package from the gentoo repository, it was present before synchronizing (in the package with the same name from your overlay). 

Andrew-Gentoo ~ # emerge -p bitmask_client

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds built with USE flags to satisfy "dev-python/pyzmq[bundled,python_targets_python2_7(-)?,-python_single_target_python2_7(-)]".
!!! One of the following packages is required to complete your request:
- dev-python/pyzmq-14.4.1::gentoo (Missing IUSE: bundled)
  (dependency required by "net-misc/bitmask_client-0.7.0_rc6::hnaparst" [ebuild])
  (dependency required by "bitmask_client" [argument])

**Comment by Harold-Anderson** [comment]
Yes, I have to update bitmask_client.  I was working on that way back when.  It looks like they have made some progress, so I'll see if I can get that back up and running for you.

**Comment by Harold-Anderson** [comment]
I will just mention that as of 0.7.0, bitmask_client was in a horrible state, which is why I abandoned work on it.  But it is probably time to see if they have their act together yet.

**Comment by Harold-Anderson** [comment]
OK, I have been able to get bitmask-0.9.1 working.  I have checked everything into my overlay and attached a screenshot.

![screenshot at 2016-03-23 18 25 40](https://cloud.githubusercontent.com/assets/5002519/14005908/234144a4-f125-11e5-9762-b4bc64a8a2a8.png)

**Comment by Nowa-Ammerlaan** [comment]
Thank you, I managed to get it working now. There is a minor issue, bitmask requires leap_mail-0.4.0, leap_pycomman-0.5.0, soledad-common-0.7.4 soledad-client-0.7.5 and keymanager-0.4.3. bitmask fails to run with older versions, however portage does not complain when the older versions are on the system instead of the newer versions, and it will just install the wrong versions as a dependency unless the newer versions are also keyworded with ~amd64. Otherwise it works fine, Thanks

**Comment by Harold-Anderson** [comment]
OK, that is fixed.  Thanks for the QA.  By the way, with black.riseup.net as a server, I am getting about 70 Mbps.  Rather impressive for a VPN.
