### ISSUE TITLE
net-misc/bitmask_client-0.9.1 file collision during install phase

### ISSUE THREAD

**Issue by mmirg** [hnaparst/overlay#8]
I tried installing bitmask_client-0.9.1 with your ebuild and I'm getting a collision with sys-apps/iproute2-4.3.0 because both packages seem to claim /sbin/ip.  Is this something you encountered or that can be resolved?  My apologies for the cross-post from the Gentoo bug tracker.

**Comment by Harold-Anderson** [comment]
I will look at it.  Give me a day or two.  In the meantime just emerge --resume --skipfirst

**Comment by Harold-Anderson** [comment]
Please give it a try now and let me know if you have any other problems.

**Comment by mmirg** [comment]
It installs now, thank you.
